image: Visual Studio 2022
version: 3.0.{build}
configuration: Release

install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Channel 10.0 -Quality GA -InstallDir "$env:ProgramFiles\dotnet"

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/JeremyAnsel.Media.WavefrontObj" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

environment:
  GITHUB_TOKEN:
    secure: awbDbCVBldNyz+7VzGnSLlBnczS0NtXrUaS7UkrwoOoUIAzE70QHYfKQuTyOJavb

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore JeremyAnsel.Media.WavefrontObj\JeremyAnsel.Media.WavefrontObj.sln

build:
  project: JeremyAnsel.Media.WavefrontObj\JeremyAnsel.Media.WavefrontObj.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal

after_build:
- if not defined APPVEYOR_PULL_REQUEST_NUMBER JeremyAnsel.Media.WavefrontObj\build-doc.cmd
- if not defined APPVEYOR_PULL_REQUEST_NUMBER 7z a JeremyAnsel.Media.WavefrontObj.Documentation.zip .\JeremyAnsel.Media.WavefrontObj\Documentation\_site\* > nul
- if not defined APPVEYOR_PULL_REQUEST_NUMBER appveyor PushArtifact JeremyAnsel.Media.WavefrontObj.Documentation.zip

test_script:
- JeremyAnsel.Media.WavefrontObj\run-tests.cmd

deploy:
- provider: NuGet
  api_key:
    secure: sUeBE3LCs5DmwaXEK8vYeAbVUaDqdhWWp47LtoRRgBBO9G6k5r/2lP6FG/FkihLY
  skip_symbols: false
  on:
    branch: master
    DEPLOY: True

after_deploy:
- if "%DEPLOY%" == "True" git clone -q --branch=gh-pages --depth 5 https://github.com/JeremyAnsel/JeremyAnsel.Media.WavefrontObj.git gh-pages
- if "%DEPLOY%" == "True" cd gh-pages
- if "%DEPLOY%" == "True" git checkout -qf gh-pages
- if "%DEPLOY%" == "True" git config core.safecrlf false
- if "%DEPLOY%" == "True" git config push.default simple
- "if \"%DEPLOY%\" == \"True\" git config user.name \"Jérémy Ansel\""
- if "%DEPLOY%" == "True" git config user.email JeremyAnsel@users.noreply.github.com
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\JeremyAnsel.Media.WavefrontObj\Documentation\_site .
- if "%DEPLOY%" == "True" git add --all . > nul
- if "%DEPLOY%" == "True" git commit -m "Update doc generated by CI" || true
- if "%DEPLOY%" == "True" if exist coverage rd /s /q coverage
- if "%DEPLOY%" == "True" md coverage
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\JeremyAnsel.Media.WavefrontObj\bld\coverage coverage
- if "%DEPLOY%" == "True" git add --all coverage > nul
- if "%DEPLOY%" == "True" git commit -m "Update code coverage generated by CI" || true
- if "%DEPLOY%" == "True" git push -q https://%GITHUB_TOKEN%@github.com/JeremyAnsel/JeremyAnsel.Media.WavefrontObj.git
